### ISSUE TITLE
Disable index updates when installing packages

### ISSUE THREAD

**Issue by mikeedwards83** [kevinobee/Sitecore.Ship#13]
When installing packages can we disable lucene so that it only updates at the end of the install.

**Comment by djanjicek** [comment]
At least in 7.2 I see this in my crawling log files: "Stopping indexing while package is being installed.", although the common log files still indicate that something is being indexes.

**Comment by pveller** [comment]
Ship will disable indexes (look at `Sitecore.Ship.Infrastructure.Update.UpdatePackageRunner`) if you tell it to via `disableIndexing` param. From looking at the code I believe only the Nancy version will honor it. The pre-Nancy Asp.Net version doesn't seem to notice it. Easy to fix with a simple pull request to @kevinobee which I will probably go ahead and do later today :)

in Asp.Net:

```csharp
private static InstallUploadPackage GetRequest(HttpRequestBase request)
{
    return new InstallUploadPackage
        {
            PackageId = request.Form["packageId"],
            Description = request.Form["description"]
        };
}
```

vs. in Nancy:

```csharp
var uploadPackage = this.Bind<InstallUploadPackage>();
```
