### ISSUE TITLE
UpdateHelper.SaveInstallationMessages removed in Sitecore 7.5

### ISSUE THREAD

**Issue by jimmah** [kevinobee/Sitecore.Ship#30]
Hi there,

It looks like Sitecore have removed the `UpdateHelper.SaveInstallationMessages` method in Sitecore 7.5, without marking it obsolete/deprecated. More info here: http://laubplusco.net/updatehelper-saveinstallationmessages-removed-sitecore-7-5/

This causes a `MissingMethodException` to be thrown when installing packages via Ship.

I've forked Ship to comment out the call to this method (in `UpdatePackerRunner.Execute`) as I don't know what the equivalent method is now. If I can figure out what it should be now, I'll send a pull request.

Thanks,
James

**Comment by kevinobee** [comment]
This was addresses by @pveller in commit 107f8d51621bfd941cd8da96deef44e4f7b6e104 and will be included in the 0.4.0 release package.

**Comment by chiragp** [comment]
@kevinobee when is the 0.4.0 release package slated to drop?  i'm getting this issue on Sitecore 8.1.

**Comment by pveller** [comment]
You can get it off of the pre-release feed: https://www.myget.org/F/sitecore-ship-prerelease/api/v2/package

The answer to your question is: soon after @kevinobee finds a maintainer to help him out :)

**Comment by chiragp** [comment]
@pveller @kevinobee Thanks.
