### ISSUE TITLE
Nancy.Json.JsonSettings.MaxJsonLength exceeded

### ISSUE THREAD

**Issue by DThrasher** [kevinobee/Sitecore.Ship#39]
When installing a large package for the Sitecore Master database (this was a multi-site solution) I recieve the following error in the Sitecore logs from Sitecore Ship:

> Exception: System.InvalidOperationException
> Message: Nancy.Json.JsonSettings.MaxJsonLength exceeded
> Source: Nancy
> [stack trace with lots of Json Serialization stuff]

When this error occurs, the items are not installed to the Sitecore instance.

Smaller packages, such as the one I used for the Core database, work just fine. 

I think the problem is that the Json string that lists the item Ids that were added to Sitecore exceeds the  mono serializer's max length. I found a handful of blog posts discussing this issue, for example: http://ouarzy.azurewebsites.net/?p=441

My feature request is a switch to disable the reporting of the item Ids.

**Comment by kevinobee** [comment]
Interesting request, do you fancy having a go at implementing it and sending through a PR?

Another approach is outlined in this post on [MaxJsonLength property with Nancy](http://ouarzy.azurewebsites.net/?p=441). This post documents increasing the max json length that your server can transfer to your client.

    JsonSettings.MaxJsonLength = Int32.MaxValue

**Comment by DThrasher** [comment]
Ok, I think I've set up my pull request properly. This is the first time I've made a pull request on GitHub, so let me know if I need to do something differently. 

I opted to add a "DisableManifest" parameter rather than to simply increase the MaxJsonLength setting, because any limit we apply is an arbitrary one. I figured it'd be cleaner to disable it altogether.

**Comment by kevinobee** [comment]
Your changes have been merged into both the *develop* and *release/0.4.0* branches.

https://github.com/kevinobee/Sitecore.Ship/commit/ddacb48dd7252ddbfb2e608a0f4b85805376d69f
