### ISSUE TITLE
Version 0.4 release date

### ISSUE THREAD

**Issue by ernstjoss** [kevinobee/Sitecore.Ship#41]
Hi KevinObee
As we work on a migration-prject to sitecore 8 and use ship to install item packages, we would need the changes in the 0.4 version to have a working one.
When do you plan to release version 0.4?
If not in the next few days, could you provide a prerelease nuget package in order we can use ship for sitecore 8?

**Comment by kevinobee** [comment]
@ernstjoss Currently getting the pre-release tests done on Ship 0.4.0. In the mmeantime there is a pre-release feed for alpha packages on [MyGet](https://www.myget.org/feed/Packages/sitecore-ship-prerelease).

All feedback very welcome.

**Comment by ernstjoss** [comment]
The correct link to the packages on myget is: https://www.myget.org/F/sitecore-ship-prerelease/

**Comment by kevinobee** [comment]
Thanks for the link correction @ernstjoss, I've updated my comment above to use the correct link.

Have you seen any issues with the pre-release packages?

**Comment by patrickperrone** [comment]
I've noticed install POSTs sometimes hang on my test site and the only way to resolve is an IISRESET. I built the package for Sitecore.Ship from the development branch.I suspect it might have something to do with NancyFx. Have you tried later versions of Nancy than 0.17.1?

**Comment by marcduiker** [comment]
I only noticed a 'hanging install' with SC8 update-4 using the default analytics configuration (enabled) while I didn't have Mongo DB's installed. The installation actually succeeded but the POST got a timeout. When I disabled the analytics in Sitecore.Analytics.config the install worked fine.

**Comment by patrickperrone** [comment]
That's a great point, Marc. My current test site is SC8.4, however, I do have MongoDB installed. I haven't tested with analytics disabled.

**Comment by ernstjoss** [comment]
@kevinobee: No issues detected so far.
I use SC8 update-4 with MongoDB's available and original SC Configs regarding to Analytics/ContentSearch.
On a Development System even a simultaneously running unicorn-synchronisation (writing out basically everything what was installed by ship) was running without any problems (well, that was not really intended, but worked smooth as well for big item-package uploads)

**Comment by kevinobee** [comment]
@ernstjoss Great to hear. Which version of Ship are you using, NancyFx or Http Handlers?

**Comment by ernstjoss** [comment]
@kevinobee We use SItecore.Ship, the one thats get registered and called through Nancy handlers.

**Comment by kevinobee** [comment]
@ernstjoss any thoughts on #43 ?

**Comment by kevinobee** [comment]
Just uploaded to MyGet feed

Sitecore.Ship.0.4.0.150818.nupkg
Sitecore.Ship.AspNet.0.4.0.150818.nupkg
