### ISSUE TITLE
White list is invalid for deployment access control ?  How to enable secure deployment ?

### ISSUE THREAD

**Issue by afengisme** [kevinobee/Sitecore.Ship#53]
Hi, 

I installed sitecore.ship version release 0.4.0
Sitecore.Ship-release-0.4.0.zip

After I set the white list in packageInstallation section:

    <Whitelist>
      <add name="local loopback" IP="127.0.0.1" />
      <add name="build server" IP="10.0.1.134" />
    </Whitelist>

I tried to access http://sitecoreship/services/about from 10.0.1.134, it is ok.
And I also accessed this url from a source machine whose IP is NOT 10.0.1.134, the access was denied:

##
401 - Unauthorized: Access is denied due to invalid credentials.
You do not have permission to view this directory or page using the credentials that you supplied.
##

But I could deploy a package via curl.exe from this machine (IP is not 10.0.1.134) :

##
PS C:\curl> .\curl.exe -i --show-error --form "path=@C:\Curl\package.update" http://sitecor
eship/services/package/install/fileupload
HTTP/1.1 100 Continue

HTTP/1.1 201 Created
Cache-Control: private
Content-Type: application/json; charset=utf-8
Location: /services/package/latestversion
Server: Microsoft-IIS/8.5
x-processing-time: 5854.0356
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Thu, 31 Dec 2015 08:04:19 GMT
Content-Length: 152

{"Entries":[{"ID":null,"Path":"/_DEV/DeployedItems.xml"},{"ID":null,"Path":"/bin/HedgehogDevelopment.SitecoreProject.Pac
kageInstallPostProcessor.dll"}]}
##

Even I set  allowRemote="FALSE" , still can do the deployment from this machine.

Are the white list configurations invalid for deployment access control ?
Is there other authentication for secure deployment ?

thanks
-Frank

**Comment by afengisme** [comment]
It is strange.
As Kevin said in https://github.com/kevinobee/Sitecore.Ship/issues/4 :

"
Support for a whitelist of IP addresses or address ranges that are allowed to access the service routes provided by Ship would be useful.
"

Both http://sitecoreship/services/about   and  http://sitecoreship/services/package/install/fileupload  are all the "service" routes , Why the whitelist only works on http://sitecoreship/services/about access ?

**Comment by afengisme** [comment]
@pveller ,  As you told in https://github.com/kevinobee/Sitecore.Ship/issues/52 , Kevin will merge token authentication feature to release branch.  I have to wait for this feature in next release to expose my ship out.

**Comment by kevinobee** [comment]
Apologies guys, I'm half way through a one month sabbatical. The merges and bugs will get my undivided attention next week as I have blocked this out for OSS work. Thanks for bearing with me and providing excellent feedback on these issues.

@pveller - I will need to recheck the token auth work that was done as there are changes in this area coming very shortly in the core product ;-)

**Comment by richardszalay** [comment]
The issue was that BaseHttpHandler continued executing even when the access check failed. I've added a fix + unit tests for this in the referenced PR.
