### ISSUE TITLE
install of TDS pkg did not seem to update new language fallback value

### ISSUE THREAD

**Issue by mmussitsch** [kevinobee/Sitecore.Ship#54]
I'm sorry if this is too specific or more of a support issue, but I just want to make sure my deployments are working fully.  
A developer changed one of the Sitecore items language fallback values from 1 to 0 in a standard values item.  The change was deployed to our local, DEV and PROD environments.  I used TDS and sync with sitecore to upload the change  locally, and it was correct and in the standard value, the value was now off.  But via DEV and PROD where Sitecore Ship is used to install the TDS pkg, the value checkbox is still checked in that same standard values item.  I checked the jobs and confirmed that the standard values item was indeed included in the pkg and listed in the install response.
Hedgehog told me to check my installer logs, but I'm not sure if Sitecore Ship offers any other details.
Is anyone aware of any such toggle values like this not installing?

Thanks.
Melissa Mussitsch

**Comment by pveller** [comment]
Was it set to 0 or "reset"? There is a big difference when it comes to how Sitecore will handle it when installing an update package. This is standard values specific. Normal items are recreated during *.update install. Standard Values, for some reason, are updated field by field.

Look into the serialized item. Do you see the field with 0 and content-length 1 or no field at all (that would be the effect of resetting it - technically, deleting the field from that item).

If field value was reset, the field won't be recorded in the serialized state and update package installer will not see it so it won't update it on the target instance.

**Comment by mmussitsch** [comment]
Thank you Pavel,

I do recall the value being reset rather than a 0 when looking at my local
sync with sitecore.  However I suspect my developer will come back and say
that he simply "unchecked" the value in sitecore.
If that is the case, perhaps the issue is that the checking and unchecking
of check boxes in that field are not correctly setting the value from 1 to
0 but rather resetting it??  Which is another issue entirely I suppose.

Thank for the response!
Melissa Mussitsch

**Comment by pveller** [comment]
Checking and unchecking a checkbox should set `1` or `0`. String fields can `reset on empty` if you chose to configure a filed this way (it's a checkbox on the field definition item under the template's section item) but I don't believe checkboxes can reset themselves. One would need to use the `Reset Fields` dialog, I believe. Anyway. If the field was reset then it's neither TDS nor Ship problem. This is how Sitecore handles fields updates when installing `__Standard values` items. Don't now why they do it this way. Most likely historical/legacy reasons.

**Comment by mmussitsch** [comment]
Thank you.  We will keep watch of these types of issues.
Separately - can someone tell me if Sitecore ship deployments load log
histories in the TEMP > _UpgradeHistory folders?  We stumbled upon this
today when our DEV server space ran out.  If so - I'm wondering if there is
a way to send these to some other drive or location as to avoid space
issues.

Thank you again.
Melissa Mussitsch

**Comment by pveller** [comment]
Again, this is not Ship. This is Sitecore. I run scheduled powershell script that keeps it clean (purge everything that's one day+ old). You can also set up an agent in Sitecore configuration (similar to how you can purge log files you don't need) and have that one take care of these for you.

**Comment by mmussitsch** [comment]
Thank you Pavel.
Sorry I assumed Ship since that's what I'm using to install.
Appreciate again your response!!  And sorry to be sending you guys novice
questions.

Melissa
