### ISSUE TITLE
Sitecore.Ship with Sitecore 8.1 Update 1

### ISSUE THREAD

**Issue by mmussitsch** [kevinobee/Sitecore.Ship#58]
Hi,
So it seems that ever since we upgraded to Sitecore 8.1 Update 1, now our Sitecore.Ship deployment steps fail.  I'm getting the below error.  Any ideas what can be done and will I need to resolve this with each release?  Also wondering what Sitecore Ship uses for installing a .update file.  There were some bugs with sitecore packaging and installation related to language fallback versions so I'm wondering if the fixes could have caused an issue too?

    <body bgcolor="white">
            <span><H1>Server Error in '/' Application.<hr width=100% size=1 color=silver></H1>
            <h2> <i>Error has occurred during file installation.</i> </h2></span>
            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">
            <b> Description: </b>An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.
            <br><br>
            <b> Exception Details: </b>Sitecore.Update.Installer.Exceptions.PostStepInstallerException: Error has occurred during file installation.<br><br>
            <b>Source Error:</b> <br><br>
            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code>
An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.</code>
                  </td>
               </tr>
            </table>
            <br>
            <b>Stack Trace:</b> <br><br>
            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code><pre>

   Sitecore.Update.Installer.Items.PostStepInstaller.Process(IProcessingContext entry, IProcessingContext context) +1500

   Sitecore.Update.Installer.Items.PostStepInstaller.Process(IProcessingContext entry, IProcessingContext context) +2042
   Sitecore.Update.Installer.DiffInstaller.InstallPackage(String path, InstallMode mode, ILog installationProcessLogger, IList`1 entries, String rollbackPackagePath, Boolean&amp; hasPostAction, String&amp; historyPath) +874
   Sitecore.Update.UpdateHelper.Install(PackageInstallationInfo info, ILog installationProcessLogger, String&amp; historyPath) +229
   Sitecore.Ship.Infrastructure.Update.UpdatePackageRunner.Execute(String packagePath, Boolean disableIndexing) +1524
   Sitecore.Ship.Core.PackageRepository.AddPackage(InstallPackage package) +152
   Sitecore.Ship.AspNet.Package.InstallUploadPackageCommand.HandleRequest(HttpContextBase context) +696
   Sitecore.Ship.AspNet.Package.InstallPackageCommand.HandleRequest(HttpContextBase context) +640
   Sitecore.Ship.AspNet.AboutCommand.HandleRequest(HttpContextBase context) +498
   Sitecore.Ship.AspNet.SitecoreShipHttpHandler.ProcessRequest(HttpContextBase context) +75
   Sitecore.Ship.AspNet.BaseHttpHandler.ProcessRequest(HttpContext context) +350
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +913
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously) +165
</pre></code>

Please advise.
Thanks.
Melissa Mussitsch

**Comment by pveller** [comment]
First, make sure it's not #30. You would need to run Ship 0.4 that you can grab from the prerelease MyGet feed (the link is in the referenced issue).

If you are running 0.4 that's ready for Sitecore 8 then the next thing to check is what you're running in the post install step. Is it TDS-built package? Did you customize the post-install step (TDS 5.5 supports it) or does it only run the built-in recursive deploy logic?

The stacktrace is inconclusive. Is it all you got? No more details in the log files? What about the trails left in the `temp` folder where Sitecore tracks package installation? Maybe you can run the same package under `DEBUG` log level?

**Comment by mmussitsch** [comment]
Hi,

It is a clone from R4.  I had to grab and modify due to the /services url
issue I had previously requiring me to adjust the path to scshipservices
instead.  Truly I'm fairly new to .Net so a Sitecore architect assisted me
with this.
We are running in TDS .update packages and are currently at version 5.5.0.6
of TDS.  We don't really have any other special deployment steps set.  It
truly is just to update the sitecore instance with the new TDS sitecore
items.

I went to the deployment logs.  Here is the entire portion.
Just so you know -- one thing I just tried, to run the
updateinstallationwizard.aspx manually on this recently upgraded server of
my new file to make sure it still works.
I got the error message:  The following errors occured during file
installation:

Access to the path
'C:\Inetpub\wwwroot\ansyscoredev1\Website\bin\HedgehogDevelopment.SitecoreProject.PackageInstallPostProcessor.dll'
is denied.

I'm going to run this by my web admins.  If there is anything else you
notice, please let me know.  Perhaps it's an issue outside of Sitecore
Ship?  Sure wish I would see this same error in the log below though.

Thanks,

Melissa

14:58:35.805496 JobRunner.Run - Running task CmdLine.
14:58:35.805496 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message = ##[section]Starting task:
Run c:\agents\agent1\tasks\curl_745_0\curl.exe)
14:58:35.805496 JobExtensionManager.OnBeforeExecuteTask
14:58:35.805496 JobExtensionManager.OnExecuteTask
14:58:35.805496 BaseLogger.LogStatus(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, scope.TimelineRecordId =
b0449ec0-a328-414e-9615-e74ac76cb1a2, record.Name = Run
c:\agents\agent1\tasks\curl_745_0\curl.exe)
14:58:35.805496 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message = Executing the following
command-line. (workingFolder = C:\agents\agent2\_work\1\s))
14:58:35.805496 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =
c:\agents\agent1\tasks\curl_745_0\curl.exe -i --insecure --show-error
--silent --form
"path=@C:\agents\agent2\_work\1\s\Ansys.TDS\bin\Package_Dev\Ansys.TDS.scitems.update"
http://cdcsitecoredev.win.ansys.com/scshipservices/package/install/fileupload
)
14:58:35.805496 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message = Error message highlight
pattern: )
14:58:35.805496 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message = Warning message highlight
pattern: )
14:58:35.805496 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message = C:\Windows\system32\cmd.exe
/c "c:\agents\agent1\tasks\curl_745_0\curl.exe -i --insecure --show-error
--silent --form
"path=@C:\agents\agent2\_work\1\s\Ansys.TDS\bin\Package_Dev\Ansys.TDS.scitems.update"
http://cdcsitecoredev.win.ansys.com/scshipservices/package/install/fileupload
")
14:58:35.805496 Entering ProcessWrapper.CreateStartInfo
14:58:35.805496    workingFolder = C:\agents\agent2\_work\1\s
14:58:35.805496    filename = C:\Windows\system32\cmd.exe
14:58:35.805496    arguments = /c
"c:\agents\agent1\tasks\curl_745_0\curl.exe -i --insecure --show-error
--silent --form
"path=@C:\agents\agent2\_work\1\s\Ansys.TDS\bin\Package_Dev\Ansys.TDS.scitems.update"
http://cdcsitecoredev.win.ansys.com/scshipservices/package/install/fileupload
"
14:58:35.805496 Leaving ProcessWrapper.CreateStartInfo
14:58:35.805496 ProcessWrapper.Start - enter
14:58:35.805496 ProcessWrapper.Start - starting process
14:58:35.805496 ProcessWrapper.Start - process started
14:58:35.805496 ProcessWrapper.Start - leave
15:00:37.776073 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message = HTTP/1.1 500 Internal
Server Error)
15:00:37.776073 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message = Cache-Control: private)
15:00:37.776073 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message = Content-Type: text/html;
charset=utf-8)
15:00:37.776073 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message = Server: Microsoft-IIS/8.5)
15:00:37.776073 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message = X-AspNet-Version: 4.0.30319)
15:00:37.776073 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message = X-Powered-By: ASP.NET)
15:00:37.776073 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message = Date: Wed, 18 May 2016
15:00:37 GMT)
15:00:37.776073 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message = Content-Length: 6443)
15:00:37.776073 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message = <!DOCTYPE html>)
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message = <html>)
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =     <head>)
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =         <title>Error has
occurred during file installation.</title>)
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =         <meta
name="viewport" content="width=device-width" />)
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =         <style>)
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =          body
{font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;} )
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =          p
{font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px})
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =          b
{font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px})
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =          H1 {
font-family:"Verdana";font-weight:normal;font-size:18pt;color:red })
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =          H2 {
font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon })
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =          pre
{font-family:"Consolas","Lucida
Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt})
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =          .marker
{font-weight: bold; color: black;text-decoration: none;})
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =          .version {color:
gray;})
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =          .error
{margin-bottom: 10px;})
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =          .expandable {
text-decoration:underline; font-weight:bold; color:navy; cursor:hand; })
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =          @media screen and
(max-width: 639px) {)
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =           pre { width:
440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; })
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =          })
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =          @media screen and
(max-width: 479px) {)
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =           pre { width:
280px; })
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =          })
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =         </style>)
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =     </head>)
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =     <body bgcolor="white">)
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =
<span><H1>Server Error in '/' Application.<hr width=100% size=1
color=silver></H1>)
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =             <h2> <i>Error
has occurred during file installation.</i> </h2></span>)
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =             <font
face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">)
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =             <b>
Description: </b>An unhandled exception occurred during the execution of
the current web request. Please review the stack trace for more information
about the error and where it originated in the code.)
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =             <br><br>)
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =             <b> Exception
Details:
</b>Sitecore.Update.Installer.Exceptions.PostStepInstallerException: Error
has occurred during file installation.<br><br>)
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =             <b>Source
Error:</b> <br><br>)
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =             <table
width=100% bgcolor="#ffffcc">)
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =                <tr>)
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =                   <td>)
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =
<code>)
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message = An unhandled exception was
generated during the execution of the current web request. Information
regarding the origin and location of the exception can be identified using
the exception stack trace below.</code>)
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =                   </td>)
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =                </tr>)
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =             </table>)
15:00:37.791680 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =             <br>)
15:00:37.807315 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =             <b>Stack
Trace:</b> <br><br>)
15:00:37.807315 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =             <table
width=100% bgcolor="#ffffcc">)
15:00:37.807315 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =                <tr>)
15:00:37.807315 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =                   <td>)
15:00:37.807315 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =
<code><pre>)
15:00:37.807315 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =
[PostStepInstallerException: Error has occurred during file installation.])
15:00:37.807315 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =
 Sitecore.Update.Installer.Items.PostStepInstaller.Process(IProcessingContext
entry, IProcessingContext context) +1500)
15:00:37.807315 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =
[PostStepInstallerException: Error has occurred during file installation.])
15:00:37.807315 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =
 Sitecore.Update.Installer.Items.PostStepInstaller.Process(IProcessingContext
entry, IProcessingContext context) +2042)
15:00:37.807315 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =
 Sitecore.Update.Installer.DiffInstaller.InstallPackage(String path,
InstallMode mode, ILog installationProcessLogger, IList`1 entries, String
rollbackPackagePath, Boolean&amp; hasPostAction, String&amp; historyPath)
+874)
15:00:37.807315 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =
 Sitecore.Update.UpdateHelper.Install(PackageInstallationInfo info, ILog
installationProcessLogger, String&amp; historyPath) +229)
15:00:37.807315 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =
 Sitecore.Ship.Infrastructure.Update.UpdatePackageRunner.Execute(String
packagePath, Boolean disableIndexing) +1524)
15:00:37.807315 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =
 Sitecore.Ship.Core.PackageRepository.AddPackage(InstallPackage package)
+152)
15:00:37.807315 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =
 Sitecore.Ship.AspNet.Package.InstallUploadPackageCommand.HandleRequest(HttpContextBase
context) +696)
15:00:37.807315 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =
 Sitecore.Ship.AspNet.Package.InstallPackageCommand.HandleRequest(HttpContextBase
context) +640)
15:00:37.807315 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =
 Sitecore.Ship.AspNet.AboutCommand.HandleRequest(HttpContextBase context)
+498)
15:00:37.807315 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =
 Sitecore.Ship.AspNet.SitecoreShipHttpHandler.ProcessRequest(HttpContextBase
context) +75)
15:00:37.807315 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =
 Sitecore.Ship.AspNet.BaseHttpHandler.ProcessRequest(HttpContext context)
+350)
15:00:37.807315 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =
 System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
+913)
15:00:37.807315 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =
 System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp;
completedSynchronously) +165)
15:00:37.807315 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message = </pre></code>)
15:00:37.807315 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =                   </td>)
15:00:37.807315 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =                </tr>)
15:00:37.807315 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =             </table>)
15:00:37.807315 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =             <br>)
15:00:37.807315 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =             <hr width=100%
size=1 color=silver>)
15:00:37.807315 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =             <b>Version
Information:</b>&nbsp;Microsoft .NET Framework Version:4.0.30319; ASP.NET
Version:4.0.30319.34274)
15:00:37.807315 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =             </font>)
15:00:37.807315 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message =     </body>)
15:00:37.807315 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message = </html>)
15:00:37.807315 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message = )
15:00:37.822950 Process logging event with task handler.
15:00:37.822950 BaseLogger.LogStatus(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, scope.TimelineRecordId =
b0449ec0-a328-414e-9615-e74ac76cb1a2, record.Name = )
15:00:37.822950 BaseLogger.LogAttachment(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, type = DistributedTask.Core.Log, name
= Run c:\agents\agent1\tasks\curl_745_0\curl.exe, path =
C:\agents\agent2\_diag\w466ef2f3-9c72-40dc-9731-fc3c96ec5ab1.log)
15:00:37.822950 JobExtensionManager.OnAfterExecuteTask
15:00:37.822950 Process logging event with context handler.
15:00:37.822950 BaseLogger.LogStatus(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, scope.TimelineRecordId =
b0449ec0-a328-414e-9615-e74ac76cb1a2, record.Name = )
15:00:37.822950 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message = ##[section]Finishing task:
CmdLine)
15:00:37.822950 JobExtensionManager.OnAfterRunTasks
15:00:37.822950 JobExtensionManager.OnBeforeFinalizeJob
15:00:37.822950 JobExtensionManager.OnFinalizeJob
15:00:37.822950 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message = Entering OnFinalizeJob)
15:00:37.822950 BaseLogger.LogConsoleMessage(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, message = Leaving OnFinalizeJob)
15:00:37.822950 JobExtensionManager.OnAfterFinalizeJob
15:00:37.838570 AgentWorkerIPCListener.Listen() - closing
15:00:37.838570 AgentWorkerIPCListener.Listen() - closed
15:00:37.838570 BaseLogger.LogAttachment(scope.JobId =
3b22052b-3468-4910-a2b9-39fadb6e337d, type = DistributedTask.Core.Log, name
= Build, path =
C:\agents\agent2\_diag\w3b22052b-3468-4910-a2b9-39fadb6e337d.log)
15:00:37.838570 BaseLogger.Dispose()
15:00:37.838570 BaseLogger.Dispose(): disposing writer Forwarding
15:00:37.838570 ForwardingWriter.Dispose()
15:00:37.838570 ForwardingWriter.Dispose() - disconnecting proxy logger

**Comment by mmussitsch** [comment]
I apologize for the lengthy post due to the log errors.  I replied via email with that one and didn't think anything of it.  
It's pretty daunting looking at it via the forum.  Sorry!

**Comment by kevinobee** [comment]
No problem. Will take a look shortly.

FYI: The 0.4.0 pre-release packages from MyGet have been pushed to the NuGet gallery and are now listed.

-----Original Message-----

**Comment by mmussitsch** [comment]
Thank you.
Again remember, new to .NET, but if I pull any updates I need to clone
again and re-do my /services to /scshipservices changes.  At the time, I
recall we mostly did global search and replaces, so it wasn't bad, but was
any option added to later releases to allow the url to be configurable?
Just wondering.

Thanks,
Melissa

**Comment by kevinobee** [comment]
Will try to give the url stem request some more focus asap.

You can get the NuGet gallery packages [here](https://www.nuget.org/packages?q=Sitecore.Ship)

**Comment by pveller** [comment]
ok. I believe I know what's happening but I can't tell you why just yet. It's not Ship if you get the same error using `updateinstallationwizard.aspx`. Actually, Ship is no magic. Sorry @kevinobee! :) It's a nicely written file upload over HTTP that later calls into the exact same API the update wizard uses. No idea why Sitecore doesn't come bundled with an HTTP API like that. Anyway. Ship does no processing of your `.update` packages whatsoever besides storing them in a `Temp` location with a GUID file name. Everything else is vanilla Sitecore APIs.

The `.update` pacakges support certain metadata. If you are curious, I would encourage you to rename `.update` to `.zip` and explore it. One of the metadata files will list the post install step (if any). This is basically a class that Sitecore will call once package is installed. TDS bakes in their `recursive deploy` processor in every `.update` package. This is the utility that can clean up items on the target Sitecore instance based on what you configure in the [deployment properties](http://hedgehogdevelopment.github.io/tds/chapter4.html#deployment-properties). It's in the `HedgehogDevelopment.SitecoreProject.PackageInstallPostProcessor.dll` that is for some reason missing or can't be loaded according to your error log.

Here's what I would do first. Open up the `.update` package and look into `added files\bin`. Do you see the mentioned Hedgehog DLL in there?

You may also want to try the latest TDS (5.5.0.11). There were some fixes related to post deploy steps in 5.5.0.9 though I am not sure it's what you're dealing with.

**Comment by kevinobee** [comment]
That thesis sounds perfectly plausible.

I echo your thoughts on....

 "Actually, Ship is no magic. Sorry @kevinobee! :) It's a nicely written file upload over HTTP that later calls into the exact same API the update wizard uses. No idea why Sitecore doesn't come bundled with an HTTP API like that."

In personal time working on an 8.2 SSC (?) based Ship API which will be a branch on this public repos, exposed and documented on Apiary.io. Would love to see this as a v1 release.

Firm intention is to maintain backwards compatibility with existing Restful API so a versioning mechanism will be required. Currently I favour using HTTP Accept headers, but after reading https://www.troyhunt.com/your-api-versioning-is-wrong-which-is/ I am very open to discussion on this.

Comments anyone?

-Kevin 

-----Original Message-----

**Comment by mmussitsch** [comment]
Thanks all, especially Pavel, you were correct.  Sitecore Ship is working
fine.  There were some issues during our Sitecore 8.1 Update 1 and
NetworkService permissions were missing from this PostProcessor.dll file.
Once it was put back, it all works.

Thanks for your help!
Melissa

**Comment by kevinobee** [comment]
@mmussitsch is this issue resolved for you now? I will close it if it is.

Many thanks @pveller - spot on advice.

**Comment by mmussitsch** [comment]
Yes it is - thank you!

**Comment by pveller** [comment]
@kevinobee, I read that article from Troy Hunt as well. Basically, now you know that you can't be right :) That said, I always liked versions in the URL. As in `/v1/` and `/v2/`. Especially for something like Ship. 

That said, your API is not business critical and won't break a running app. The maximum damage it can do is a broken deploy pipeline. An annoying inconvenience when you manage 100s of them but even then not really a big deal. So maybe just don't version? :)
